export const mockUsers = [
  {
    id: "1",
    name: "Sarah Chen",
    email: "sarah@example.com",
    avatar: "/placeholder.svg?height=100&width=100",
    location: "San Francisco, CA",
    bio: "Full-stack developer passionate about teaching and learning new technologies.",
    skillsOffered: ["JavaScript", "React", "Node.js", "Python"],
    skillsWanted: ["Machine Learning", "UI/UX Design", "Spanish"],
    availability: ["evenings", "weekends"],
    isPublic: true,
    rating: 4.8,
    role: "user" as const,
    status: "active",
  },
  {
    id: "2",
    name: "Marcus Johnson",
    email: "marcus@example.com",
    avatar: "/placeholder.svg?height=100&width=100",
    location: "New York, NY",
    bio: "Designer and photographer with 8 years of experience.",
    skillsOffered: ["UI/UX Design", "Photography", "Adobe Creative Suite"],
    skillsWanted: ["JavaScript", "Marketing", "French"],
    availability: ["flexible"],
    isPublic: true,
    rating: 4.6,
    role: "user" as const,
    status: "active",
  },
  {
    id: "3",
    name: "Elena Rodriguez",
    email: "elena@example.com",
    avatar: "/placeholder.svg?height=100&width=100",
    location: "Austin, TX",
    bio: "Marketing professional and language enthusiast.",
    skillsOffered: ["Digital Marketing", "Spanish", "Content Writing"],
    skillsWanted: ["Data Analysis", "Python", "Guitar"],
    availability: ["weekends"],
    isPublic: true,
    rating: 4.9,
    role: "user" as const,
    status: "active",
  },
  {
    id: "4",
    name: "David Kim",
    email: "david@example.com",
    avatar: "/placeholder.svg?height=100&width=100",
    location: "Seattle, WA",
    bio: "Data scientist and machine learning engineer.",
    skillsOffered: ["Machine Learning", "Data Analysis", "Python"],
    skillsWanted: ["Web Development", "Design", "Japanese"],
    availability: ["evenings"],
    isPublic: true,
    rating: 4.7,
    role: "user" as const,
    status: "active",
  },
  {
    id: "5",
    name: "Lisa Thompson",
    email: "lisa@example.com",
    avatar: "/placeholder.svg?height=100&width=100",
    location: "Denver, CO",
    bio: "Project manager with expertise in agile methodologies.",
    skillsOffered: ["Project Management", "Agile", "Leadership"],
    skillsWanted: ["Photography", "Italian", "Guitar"],
    availability: ["flexible"],
    isPublic: true,
    rating: 4.7,
    role: "user" as const,
    status: "active",
  },
  {
    id: "admin",
    name: "Admin User",
    email: "admin@skillswap.com",
    avatar: "/placeholder.svg?height=100&width=100",
    location: "Platform Admin",
    bio: "Platform administrator with full access to moderation and management tools.",
    skillsOffered: ["Platform Management", "User Support", "Data Analysis"],
    skillsWanted: ["Community Building", "Content Strategy"],
    availability: ["business hours"],
    isPublic: false,
    rating: 5.0,
    role: "admin" as const,
    status: "active",
  },
]

export const mockRequests = [
  {
    id: "req-1",
    senderId: "2",
    receiverId: "1",
    senderName: "Marcus Johnson",
    receiverName: "Sarah Chen",
    senderAvatar: "/placeholder.svg?height=100&width=100",
    receiverAvatar: "/placeholder.svg?height=100&width=100",
    skillOffered: "UI/UX Design",
    skillWanted: "JavaScript",
    message:
      "Hi Sarah! I'd love to learn JavaScript from you. I have 8 years of design experience and would be happy to teach you UI/UX principles in return.",
    status: "pending" as const,
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "req-2",
    senderId: "1",
    receiverId: "4",
    senderName: "Sarah Chen",
    receiverName: "David Kim",
    senderAvatar: "/placeholder.svg?height=100&width=100",
    receiverAvatar: "/placeholder.svg?height=100&width=100",
    skillOffered: "Python",
    skillWanted: "Machine Learning",
    message:
      "Hey David! I'm really interested in learning ML. I can help you with Python fundamentals and web development.",
    status: "accepted" as const,
    createdAt: "2024-01-14T14:30:00Z",
  },
  {
    id: "req-3",
    senderId: "3",
    receiverId: "1",
    senderName: "Elena Rodriguez",
    receiverName: "Sarah Chen",
    senderAvatar: "/placeholder.svg?height=100&width=100",
    receiverAvatar: "/placeholder.svg?height=100&width=100",
    skillOffered: "Digital Marketing",
    skillWanted: "React",
    message:
      "Hi! I'd love to learn React development. I can teach you digital marketing strategies that have worked well for my clients.",
    status: "completed" as const,
    createdAt: "2024-01-10T09:15:00Z",
    completedAt: "2024-01-20T16:00:00Z",
  },
  {
    id: "req-4",
    senderId: "5",
    receiverId: "2",
    senderName: "Lisa Thompson",
    receiverName: "Marcus Johnson",
    senderAvatar: "/placeholder.svg?height=100&width=100",
    receiverAvatar: "/placeholder.svg?height=100&width=100",
    skillOffered: "Project Management",
    skillWanted: "Photography",
    message:
      "I'm interested in learning photography for my personal projects. I can share project management methodologies that might help with your client work.",
    status: "rejected" as const,
    createdAt: "2024-01-12T11:45:00Z",
  },
]
